import assert from "node:assert/strict";
import test from "node:test";
import { mergeSyncSnapshots, seedSyncMetadata, stampSnapshotChanges, type CloudSnapshotV2 } from "../src/index.js";

const snapshot = (): CloudSnapshotV2 => ({ schemaVersion: 2, queueMasterId: "account", settings: null, workspace: { startedAt: "2026-01-01T00:00:00.000Z", endedAt: null, lateArrivalCutoffAt: null, matchmakingAlgorithm: "v3", matchmakingRevision: 1, version: 1 }, players: [{ id: "p1", displayName: "Alice", gender: "FEMALE", skillLevel: "BEGINNER", skillWeight: 2, status: "ACTIVE" }], queuePlayers: [], courts: [], matches: [], feeConfig: null, payments: [], audits: [] });
const participant = (id: string, queuePlayerId: string, team: "A" | "B", teamSlot: number) => ({ id, matchId: "match-1", queuePlayerId, team, teamSlot, priorQueueEnteredAt: null });
const lineupSnapshot = (): CloudSnapshotV2 => { const result = snapshot(); result.players = ["p1", "p2", "p3", "p4", "p5"].map((id, index) => ({ id, displayName: `Player ${index + 1}`, gender: index % 2 ? "MALE" : "FEMALE", skillLevel: "BEGINNER", skillWeight: 2, status: "ACTIVE" })); result.queuePlayers = result.players.map((player, index) => ({ id: `q${index + 1}`, playerId: player.id, displayName: player.displayName, gender: player.gender, skillLevel: player.skillLevel, skillWeight: player.skillWeight, status: "QUEUED", matchesPlayed: 0, wins: 0, losses: 0, pointsFor: 0, pointsAgainst: 0, amountDueMinor: 0, manualPriority: 0, priorityReason: null, latePenaltyState: null, latePenaltyAppliedAt: null, queueEnteredAt: null, lastMatchEndedAt: null, currentMatchId: "match-1", checkedInAt: null, checkedOutAt: null, restStartedAt: null, version: 1 })); result.matches = [{ id: "match-1", courtId: null, courtIdSnapshot: null, courtNameSnapshot: null, status: "QUEUED", source: "AUTOMATIC", matchmakingMode: "BALANCED", algorithmVersion: "v3", suggestionKey: "suggestion-1", suggestionExplanation: null, pointsToWin: 31, winBy: 1, scoreCap: 31, bestOf: 1, queuedAt: "2026-01-01T01:00:00.000Z", startedAt: null, completedAt: null, cancelledAt: null, cancellationReason: null, winnerTeam: null, currentRevisionId: null, version: 1, participants: [participant("remote-1", "q1", "A", 1), participant("remote-2", "q2", "A", 2), participant("remote-3", "q3", "B", 1), participant("remote-4", "q4", "B", 2)], scoreRevisions: [] }]; return result; };

test("edited match participants are selected as one aggregate", () => { const remote = lineupSnapshot(); const local = structuredClone(remote); local.matches[0] = { ...local.matches[0]!, status: "CANCELLED", version: 2, participants: [participant("local-1", "q1", "A", 1), participant("local-2", "q2", "A", 2), participant("local-3", "q3", "B", 1), participant("local-4", "q5", "B", 2)] }; const localMeta = stampSnapshotChanges(remote, local, seedSyncMetadata(remote, "device", "2026-01-01T00:00:00.000Z"), "device", "2026-01-01T02:00:00.000Z", 1); const merged = mergeSyncSnapshots(local, remote, localMeta, seedSyncMetadata(remote, "cloud", "1970-01-01T00:00:00.000Z")).snapshot.matches[0]!.participants; assert.deepEqual(merged.map((item) => item.queuePlayerId), ["q1", "q2", "q3", "q5"]); assert.equal(new Set(merged.map((item) => item.queuePlayerId)).size, 4); });
